### ISSUE TITLE
valheim linux dedicated server (valheim+ mod) - unable to stop server via ctrl+c/sigint

### ISSUE THREAD

**Issue by xanathos79** [NeighTools/UnityDoorstop#11]
Hi,

I'm opening this issue on both doorstop and BepInEx as I'm not sure on which of these the actual problem is.
The regular Valheim server can be stopped via ctrl+c or by sending a sigint to the PID.
After installing the Valheim+ mod, which contains BepInEx and Doorstop, the server starts as usual but neither control+c on the console or sending a sigint works to gracefully stop the server.
Killing the server via sigterm/sigkill can leave the world data corrupted.

Let me know if you need any additional data, I'm happy to help where possible.

**Comment by xanathos79** [comment]
Ticket on Valheim+: https://github.com/nxPublic/ValheimPlus/issues/65

**Comment by ghorsington** [comment]
Greetings!

I'm closing the issue here as it is not related to Doorstop. Moreover, this repository is for Windows version of Doorstop and not Linux one.
