### ISSUE TITLE
UnityDoorstop doesn't load when doorstop_config.ini is written in UTF-8 with BOM

### ISSUE THREAD

**Issue by sebastienvercammen** [NeighTools/UnityDoorstop#13]
Hi there,

Using C# targeting .NET 4.0 and 4.5 (tested separately), I used [`File.WriteAllText`](https://docs.microsoft.com/en-us/dotnet/api/system.io.file.writealltext?view=netframework-4.5) to write changes to my `doorstop_config.ini`.

With the following code, this writes as UTF-8 with BOM:

```cs
File.WriteAllText(path, contents, Encoding.UTF8);
```

And this broke UnityDoorstop. It just wouldn't load.

Changing the file write to UTF-8 without BOM (explicit) fixed it:

```cs
File.WriteAllText(path, contents, new UTF8Encoding(false));
```

**Comment by ghorsington** [comment]
Doorstop makes use of WinAPI's [`GetPrivateProfileStringW `](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-getprivateprofilestringw) to read its INI file and thus how the configs are read depend on that.  

There is no intention on changing the API or implementing one as the one provided by Windows works fine for the purposes of Doorstop. As such, I'm marking this as a wontfix and closing this issue.

I've updated the wiki page to note that the config file must not have a byte order mark.
