### ISSUE TITLE
Can't build "memcpy already defined"

### ISSUE THREAD

**Issue by guidra-rev** [NeighTools/UnityDoorstop#18]
I'm trying to build the solution with Visual Studio 2019, I receive the following error :

libvcruntime.lib(memcpy.obj) : error LNK2005: memcpy already defined in crt.obj
C:\...\UnityDoorstop\Proxy\bin\x64\Debug\proxy.dll : fatal error LNK1169: one or more multiply defined symbols found

I can't figure out what is the issue, must be related to this in `crt.h`
```
extern void *memcpy(void *dst, const void *src, size_t n);
#pragma intrinsic(memcpy)
```

**Comment by ghorsington** [comment]
Closing as old. Doorstop source has been since rewritten and the build tools got entirely changed from VS to xmake, which should alleviate the problem.
