### ISSUE TITLE
Doorstop not working on first Steam Launch.

### ISSUE THREAD

**Issue by TeKGameR950** [NeighTools/UnityDoorstop#32]
Hi, i'm still facing the issue #5  with Raft.

When opening the game through steam the first time, it does not load at all, i think it might be related, could we have a setting to toggle the double injection ? my code anyway checks if its already loaded.

**Comment by ghorsington** [comment]
Greetings!

Just as with #5, I cannot really help without any extra info or logs. Doorstop 4 releases nowadays include debug/verbose builds that emit Doorstop logs. Please use those and include any logs you get.

PS: I am not sure what you mean by "double injection", but both Doorstop 3 and Doorstop 4 include a config option named `ignore_disable_switch`/`ignoreDisableSwitch` to disable checking if Doorstop is already initialized.

**Comment by TeKGameR950** [comment]
Oh, yeah the "ignore_disable_switch" setting worked.
Basically, when starting the game without steam, it "apparently" kill the process and restart the game but this time doorstop doesn't work.
But with the disable switch it perfectly works :)

Thanks.
