### ISSUE TITLE
Have a release zip include all archs and versions

### ISSUE THREAD

**Issue by CptMoore** [NeighTools/UnityDoorstop#35]
As part of the [ModTek ](https://github.com/BattletechModders/ModTek) release, I include all ARCH variants. To make debugging easier, I would also like to include the verbose variants in a subfolder ready just for copy/pasting.

Right now as part of the build process of ModTek, it has to download three zips from here, and it would need to download three more for the verbose variants.

It would be simpler to just have one zip with all variants.

**Comment by ghorsington** [comment]
Greetings!

I personally don't see an issue with downloading different ZIPs. They are all small so even without parallelization the process is quite fast and just a few lines long (for example in [BepInEx builds script it's just a simple enumerator](https://github.com/BepInEx/BepInEx/blob/master/build/Program.cs#L171-L177)).

If you need it (or someone else does), I'll happily accept a PR.

**Comment by CptMoore** [comment]
I agree about them being small.
It does bloat the build code if using msbuild directly, and github itself would appreciate less requests (we actually had github actions fail because of global limits).
Ill try to contribute this
