### ISSUE TITLE
[question] about ignoreDisableSwitch

### ISSUE THREAD

**Issue by guilherme-gm** [NeighTools/UnityDoorstop#38]
Hello,

First of all, I am totally new to modding unity games and also to doorstop, just found about it a few days ago when checking out bepinex.

I would like to ask where I can get more information about `ignoreDisableSwitch`. Checking the config file and the `DOORSTOP_DISABLE` documentation I understand that this config would ignore an env var that disables Doorstop.

But I have some questions:
1. Why would I want to specifically disable it via an environment var? is there a known use case?
2. What are the risks of enabling `ignoreDisableSwitch`? as there is an alert that suggests it has some risks

I recently had an issue where a steam game was restarting just after it launched and disabling bepinex, changing this config in doorstop to true made it work, but I am clueless about why would I want it as false, or if there is a risk around using it as true.

Thanks in advance

**Comment by ghorsington** [comment]
Greetings!

You can look at the comment in https://github.com/NeighTools/UnityDoorstop/issues/34#issuecomment-1251871684 for information on why the option was originally made and how it works.

**Comment by guilherme-gm** [comment]
Thank you very much!
