### ISSUE TITLE
output_log being written to C:\User\ouput_log.txt

### ISSUE THREAD

**Issue by TeKGameR950** [NeighTools/UnityDoorstop#39]
Hi, on some system of my users or on my dedicated server running win server 2022, for some reasons the redirect output log redirects the output log to C:\User\output_log.

Any idea why this happens ? the doorstop dll is next to the game, works perfectly but for some reasons this happens.
Here's my full path in case it can help.
C:\Users\Administrator\Desktop\RM PLACE

**Comment by Ecorous** [comment]
I'm running into this issue on SpiderHeck with Proton and the latest doorstop release

**Comment by ManlyMarco** [comment]
Fixed by #50
