### ISSUE TITLE
--doorstop-mono-debug-suspend true

### ISSUE THREAD

**Issue by jbrazio** [NeighTools/UnityDoorstop#42]
Hi, I'm starting by game process with the additional command line args:
`--doorstop-mono-debug-enabled true --doorstop-mono-debug-address "0.0.0.0:55555" --doorstop-mono-debug-suspend true`

All works as expected, I'm able to connect to the port `55555` from dnSpy and the process is suspended, the only loaded module is `mscorlib.dll`. My question is, how do I exist the suspend state on UnityDoorstop from dnSpy ? For the debugger the process is already in a running state.. so even if I pause and start it will continue to be suspended.

**Comment by ManlyMarco** [comment]
Make sure you don't have debugger detection prevention enabled in dnspy.

**Comment by ManlyMarco** [comment]
Closing stale issue.
