### ISSUE TITLE
UnityDoorstop can't work!

### ISSUE THREAD

**Issue by Yan-Zero** [NeighTools/UnityDoorstop#5]
I find that UnityDoorstop can't work in sometime.
But I don't know why.
(This problem maybe cause as some optimization

My friend also has this problem.

I test the Example "Doorstop.dll". It's can't work too. 
So I consider that it is the problem of UnityDoorstop.

**Comment by denikson** [comment]
Greetings!

Please provide some more information. What game are you trying it on? What version of Doorstop are you using and what build (x86/x64)? What does your configuration file look like? How did you install Doorstop? Do you use any antivirus software and if so, which one?

Without having any information I cannot reproduce the issue at all. As such, I unfortunately cannot help until you elaborate on your issue more. Just saying "it doesn't work for me so it obviously is tool's issue" doesn't help me.

**Comment by Yan-Zero** [comment]
> Greetings!
> 
> Please provide some more information. What game are you trying it on? What version of Doorstop are you using and what build (x86/x64)? What does your configuration file look like? How did you install Doorstop? Do you use any antivirus software and if so, which one?
> 
> Without having any information I cannot reproduce the issue at all. As such, I unfortunately cannot help until you elaborate on your issue more. Just saying "it doesn't work for me so it obviously is tool's issue" doesn't help me.

hmmmmmm. Game is "Scroll Of Taiwu". All version of the doorstop (x86/x64) was tested at that time.This problem has been.

But my friend found that the "winhttp.dll" was loaded.
I prepare for testing in more way such as changing a Unity game and writing a doorstop.dll by myself etc.

All  right, UnityDoorstop can run again.
Maybe, because I rebooted my computer.
Wait awhile,please.I try reconstructing it.

**Comment by Yan-Zero** [comment]
I found that it won't work if I start game from exe of game before Steam running.
Then it won't work until Steam restarting

**Comment by denikson** [comment]
Thank you for all this information!

I managed to replicate this issue. It seems that when the game is run without Steam open, it opens an extra process. Doorstop is made to not load itself twice in the same process in order to prevent issues with some games.

Please try Doorstop below:
[winhttp.zip](https://github.com/NeighTools/UnityDoorstop/files/4398586/winhttp.zip)

Please restart your computer after installing this Doorstop. It seems that the change doesn't come into effect before you restart it. 

I tested this build with Scroll of Taiwu just like you described, and it works fine.
Please verify that it works on your side as well.

**Comment by Yan-Zero** [comment]
> Thank you for all this information!
> 
> I managed to replicate this issue. It seems that when the game is run without Steam open, it opens an extra process. Doorstop is made to not load itself twice in the same process in order to prevent issues with some games.
> 
> Please try Doorstop below:
> [winhttp.zip](https://github.com/NeighTools/UnityDoorstop/files/4398586/winhttp.zip)
> 
> Please restart your computer after installing this Doorstop. It seems that the change doesn't come into effect before you restart it.
> 
> I tested this build with Scroll of Taiwu just like you described, and it works fine.
> Please verify that it works on your side as well.
> 
> EDIT: Do note that the game you're trying to edit has its Assembly-CSharp encrypted. It's not overly difficult to extract the original one, but while you haven't, you won't be able to really do anything meaningful with the game in terms of modding.

Thanks for your work.
It can work well now.

**Comment by bugproof** [comment]
It doesn't work for me neither. 

```
Doorstop started!
App dir: C:\Program Files (x86)\Steam\steamapps\common\Valheim
Working dir: C:\Program Files (x86)\Steam\steamapps\common\Valheim
STDOUT handle at 0000000000000000
Pointer to GetFinalPathNameByHandleA 00007FFCC2F34DC0
STDOUT handle path: 
DLL Path: C:\Program Files (x86)\Steam\steamapps\common\Valheim\WINHTTP.dll
EXE Path: C:\Program Files (x86)\Steam\steamapps\common\Valheim\valheim.exe
Doorstop DLL Name: WINHTTP
Looking for original DLL from C:\Program Files (x86)\Steam\steamapps\common\Valheim\WINHTTP_alt.dll
Looking for original DLL from C:\WINDOWS\system32\WINHTTP.dll
Config; Target assembly: C:\Program Files (x86)\Steam\steamapps\common\Valheim\Doorstop.dll
Redirected output log!
CMDLine: "C:\Program Files (x86)\Steam\steamapps\common\Valheim\valheim.exe"  -logFile "C:\Program Files (x86)\Steam\steamapps\common\Valheim\output_log.txt"
Doorstop enabled!
Installing IAT hook
Hook installed!!
Got mono.dll at 00007FFC72920000
Loaded all mono.dll functions
Starting mono domain
STDOUT handle at 0000000000000000
STDOUT handle path: 
Setting config paths: base dir: C:\Program Files (x86)\Steam\steamapps\common\Valheim\; config path: C:\Program Files (x86)\Steam\steamapps\common\Valheim\valheim.exe.config
Assembly dir: C:\Program Files (x86)\Steam\steamapps\common\Valheim\valheim_Data\Managed
Loading assembly: C:\Program Files (x86)\Steam\steamapps\common\Valheim\Doorstop.dll
Invoking method!
```

**Comment by TeKGameR950** [comment]
Hi, i'm still facing this issue with Raft.

When opening the game through steam the first time, it does not load at all, i think it might be related, could we have a setting to toggle the double injection ? my code anyway checks if its already loaded.

**Comment by Vapok** [comment]
@ghorsington  - I hate to bring up an old thread, but I'm running into a similar issue on a new game called ASKA.  It's running Unity 2022.3.12f, MonoBehavior compiled with IL2CPP.

Current 4.3 version of Doorstop does not seem to work.  Nothing happens.  (I'm using this in conjuction with BepInEx 6.0-pre2 (as well as BE), which is also using version 4.3.

Reason I am bringing this thread back up is for context.  The DLL you posted above for the other commenter to try... appears to be the only DLL where Doorstop appears to do anything.

Nothing happens with the current packaged version.. however the version you provided gives this log out:

```
Doorstop started!
App dir: G:\Steam\steamapps\common\ASKA Modded
Working dir: G:\Steam\steamapps\common\ASKA Modded
STDOUT handle at 0000000000000000
Pointer to GetFinalPathNameByHandleA 00007FF992DA06C0
STDOUT handle path: 
DLL Path: G:\Steam\steamapps\common\ASKA Modded\WINHTTP.dll
EXE Path: G:\Steam\steamapps\common\ASKA Modded\Aska.exe
Doorstop DLL Name: WINHTTP
Looking for original DLL from G:\Steam\steamapps\common\ASKA Modded\WINHTTP_alt.dll
Looking for original DLL from C:\WINDOWS\system32\WINHTTP.dll
Config; Target assembly: G:\Steam\steamapps\common\ASKA Modded\Doorstop.dll
Could not find target assembly! Cannot enable!Doorstop disabled! memfreeing resources
```
Which I noticed this DLL you linked appears to not respect the doorstop_config.ini where it's supposed to be looking for the BepInEx Core IL2CPP DLL.

What do I do here?

**Comment by ManlyMarco** [comment]
@Vapok Horse is long MIA. It just looks like a verbose doorstop build, you can get one from releases on this repo and it should spawn a log file for every time doorstop is triggered.

**Comment by Vapok** [comment]
@ManlyMarco I'm actually using the latest on this repo, 4.3. and it's not spawning any logs.. but that zip linked a few posts up.. DOES...

**Comment by Vapok** [comment]
I see... the "Verbose" one does logging.
